Library/Models/Catalog/AssetDetailModel.cs
using LibraryData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Catalog
{
    public class AssetDetailModel
    {
        public string AssetId { get; set; }
        public string Title { get; set; }
        public string AuthorOrDirector { get; set; }
        public string Type { get; set; }
        public string Year { get; set; }
        public string ISBN { get; set; }
        public string DeweyCallNumber { get; set; }
        public string Status { get; set; }
        public string Cost { get; set; }
        public string CurrentLocation { get; set; }
        public string ImageUrl { get; set; }
        public string PatronName { get; set; }
        public Checkouts LastestCheckout { get; set; }
        public IEnumerable<CheckOutHistory> CheckoutHistoy { get; set; }
        public IEnumerable<Holds>CurrentHolds { get; set; }

    
    }


    public class assetHoldModel
    {

        public string PatronName { get; set; }
        public DateTime HoldPlaced { get; set; }
    }
}

Library/Models/Catalog/AssetindexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Catalog
{
    public class AssetindexModel
    {

        public IEnumerable<AssetindexlistingModel> Assets { get; set; }
    }
}

Library/Models/Catalog/AssetindexlistingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Catalog
{
    public class AssetindexlistingModel
    {


        public int id { get; set; }

        public string Imgurl { get; set; }
        public string Title { get; set; }
        public string AuthorOrDirector { get; set; }
        public string Type { get; set; }

        public string NumberOfCopies { get; set; }
        public string DeweyCallNumber { get; set; }
    }
}

Library/Models/ErrorViewModel.cs
using System;

namespace Library.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Library/Models/Patron/ListOfPatronModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Patron
{
    public class ListOfPatronModel
    {

        public IEnumerable<PatronModel> Patrons { get; set; }
    }
}

Library/Models/Patron/PatronModel.cs
using LibraryData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Patron
{
    public class PatronModel
    {
        public int id { get; set; }

        public string FristName { get; set; }
        public string LastName { get; set; }

        public string FullName { get { return FristName + " " + LastName; } }
        public int LibraryCardId { get; set; }
        public string Address { get; set; }
        public DateTime MemberSice { get; set; }
        public string Telephone { get; set; }

        public string LibraryBranch { get; set; }
        public decimal Fees { get; set; }
        public IEnumerable<Checkouts> AssetsCheckedOut { get; set; }
        public IEnumerable<CheckOutHistory> CheckOutHistory { get; set; }
        public IEnumerable<Holds> Holds { get; set; }

    }
}

Library/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Models.Catalog;
using LibraryData;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class CatalogController : Controller
    {
        private LibraryData.IService _assetsService;

        //constractor
        public CatalogController(LibraryData.IService service)
        {
            this._assetsService = service;
        }




        public IActionResult Index()
        {
            var assetModels = _assetsService.GetAll();



            var listingResult = assetModels

                .Select(a => new AssetindexlistingModel

                {
                    id = a.Id,

                    Imgurl = a.ImgUrl,

                    AuthorOrDirector = _assetsService.GetAuthorOrDirector(a.Id),

                    DeweyCallNumber = _assetsService.GetDeweyIndex(a.Id),

                  //  CopiesAvailable = _checkoutsService.GetNumberOfCopies(a.Id), // Remove

                    Title = _assetsService.GetTitle(a.Id),

                    Type = _assetsService.GetType(a.Id),

                 //   NumberOfCopies = _checkoutsService.GetNumberOfCopies(a.Id)

                }).ToList();



            var model = new AssetindexModel

            {

                Assets = listingResult

            };

          

            return View(model);

        }


        public IActionResult Detail(int id)
        {


            var asset = _assetsService.GetByID(id);

            var model = new AssetDetailModel
            {

                AssetId = id.ToString(),
                Title = asset.Title,
                Year = asset.Year.ToString(),
                Cost = asset.Cost.ToString(),
                Status = asset.Status.Name,
                ImageUrl = asset.ImgUrl,
                AuthorOrDirector = _assetsService.GetAuthorOrDirector(id),
                CurrentLocation = _assetsService.GetCurrentLocation(id).Name,
                DeweyCallNumber = _assetsService.GetDeweyIndex(id),
                ISBN = _assetsService.GetIsbn(id),
            };

            return View(model);


        }


    }
}

Library/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Library.Models;

namespace Library.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Library/Controllers/PatronController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Models.Patron;
using LibraryData;
using LibraryData.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class PatronController : Controller
    {
        private IPatron _patron;
        public PatronController( IPatron patron)
        {
            this._patron = patron;

        }
        public IActionResult Index()
        {
            var allpatrons = _patron.GetAll();
            var patronModel = allpatrons.Select(p => new PatronModel
            {
                id = p.id,
                FristName = p.FristName,
                LastName = p.LastName,
                LibraryCardId = p.LibaryCard.Id,
                Fees = p.LibaryCard.Fees,
                LibraryBranch = p.LibraryBranch.Name
            }).ToList();

            var model = new ListOfPatronModel()
            {
                Patrons = patronModel
            };
            return View(model);
        }

        public IActionResult detalis( int id)
        {

            var patron = _patron.Get(id);

            var model = new PatronModel
            {
                id = patron.id,
                FristName = patron.FristName,
                LastName = patron.LastName,
                LibraryCardId = patron.LibaryCard.Id,
                Fees = patron.LibaryCard.Fees,
                LibraryBranch = patron.LibraryBranch.Name,
                Telephone = patron.TelephoneNumber,
               AssetsCheckedOut = _patron.GetCheckout(id).ToList() ?? new List<Checkouts>(),
                CheckOutHistory=_patron.CheckoutHistory(id),
                Holds= _patron.GetHolds(id)
            };
            return View(model);
        }
    }
}

Library/Views/Catalog/Detail.cshtml
@model Library.Models.Catalog.AssetDetailModel

<div class="container">
    <div class="page-header clearfix detailHeading">
        <h2 class="text-muted"> View Library Item</h2>
    </div>
</div>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            <div>
                <img style="height:300px;width:300px" src="@Model.ImageUrl" class="detailImage" />
            </div>
        </div>
        <div class="col-md-4" style="float:right">
            <p id="itemTitle">@Model.Title</p>
            <p id="itemAuthor">@Model.AuthorOrDirector</p>
            <p id="itemStatus">@Model.Status</p>
            <p id="itemType">@Model.Type</p>
            <p id="itemLocation">@Model.CurrentLocation</p>

            @if (Model.Status == "Lost")
            {
                <p> This item has been lost, it cannot be checked out .</p>
                <p> <a class="btn btn-lg btn-info" role="button" asp-controller="catalog" asp-action="MarkFound" asp-route="@Model.AssetId">Mark Item Found</a></p>

            }

            @if (Model.Status == "Checked Out")
            {
                <p id="itemPatron">Checked Out by :@Model.PatronName</p>
                <p> <a class="btn btn-lg btn-info" role="button" asp-controller="catalog" asp-action="CheckIn" asp-route="@Model.AssetId">Check In</a></p>
                <p> <a class="btn btn-lg btn-info" role="button" asp-controller="catalog" asp-action="Hold" asp-route="@Model.AssetId">Place Hold</a></p>

            }
            @if (Model.Status == "Available")
            {
                <p> <a href="@Url.Action("Checkout","catalog",Model.AssetId)" class="btn btn-lg btn-info" role="button">Check Out</a></p>

                //  <p> <a class="btn btn-lg btn-info" role="button" asp-controller="catalog" asp-action="Checkout" asp-route="@Model.AssetId">Check Out</a></p>

            }



        </div>



        <div class="col-md-4" detailInfo style="float:right">
            <table>
                <tr>
                    <td class="itemLable"> ISBN :</td>
                    <td class="itemValue">@Model.ISBN </td>
                </tr>
                <tr>
                    <td class="itemLable"> Call Number :</td>
                    <td class="itemValue">@Model.DeweyCallNumber </td>
                </tr>
                <tr>
                    <td class="itemLable">Replacement Cost:</td>
                    <td class="itemValue">@Model.Cost </td>
                </tr>
            </table>

        </div>
    </div>
</div>

Library/Views/Catalog/Index.cshtml
@model Library.Models.Catalog.AssetindexModel

@{

    ViewBag.Title = "Library Catalog Index";

}



<div id="assets">

    <h3>Library Catalog</h3>

    <div id="assetsTable">

        <table class="table table-condensed" id="catalogIndexTable">

            <thead>

                <tr>
                    <th>Image</th>

                    <th>Title</th>

                    <th>Author / Director</th>

                    <th>Dewey Call Number</th>

                </tr>

            </thead>

            <tbody>

                @foreach (var asset in @Model.Assets)

                {

                    <tr class="assetRow">

                        <td class="">

                            <div>
                                <a asp-controller="Catalog" asp-action="Detail" asp-route-id="@asset.id">

                                    <img style="height:200px" src="@asset.Imgurl" class="imageCell" />

                                </a>

                            </div>

                        </td>

                        <td class="">@asset.Title</td>

                        <td class="">@asset.AuthorOrDirector</td>

                        <td class="">@asset.DeweyCallNumber</td>

                    </tr>

                }

            </tbody>

        </table>

    </div>

</div>

Library/Views/Catalog/test.cshtml
@model Library.Models.Catalog.AssetDetailModel

<div class="container">
    <div class="page-header clearfix detailHeading" >
            <h2 class="text-muted"> View Library Item</h2>
     </div>
</div>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            <div>
                <img src="@Model.ImageUrl" class="detailImage" />
            </div>
        </div>
        <div class="col-md-4">
            <p id="itemTitle">@Model.Title</p>
            <p id="itemAuthor">@Model.AuthorOrDirector</p>
            <p id="itemStatus">@Model.Status</p>
            <p id="itemType">@Model.Type</p>
            <p id="itemLocation">@Model.CurrentLocation</p>

            @if (Model.Status == "Lost")
            {
                <p> This item has been lost, it cannot be checked out .</p>
                <p> <a   class="btn btn-lg btn-info" role="button" asp-controller="catalog" asp-action="MarkFound" asp-route="@Model.AssetId">Mark Item Found</a></p>

            }

            @if (Model.Status == "Checked Out")
            {
                <p id="itemPatron">Checked Out by :@Model.PatronName</p>
                <p> <a class="btn btn-lg btn-info" role="button" asp-controller="catalog" asp-action="CheckIn" asp-route="@Model.AssetId">Check In</a></p>
                <p> <a   class="btn btn-lg btn-info" role="button" asp-controller="catalog" asp-action="Hold" asp-route="@Model.AssetId">Place Hold</a></p>

            }
            @if (Model.Status == "Available")
            {
                <p> <a href="#" class="btn btn-lg btn-info" role="button" asp-controller="catalog" asp-action="Checkout" asp-route="@Model.AssetId">Check Out</a></p>

            }

            <div class="col-md-4" detailInfo>
                <table>
                    <tr>
                        <td class="itemLable"> ISBN :</td>
                        <td class="itemValue">@Model.ISBN </td>
                    </tr>
                    <tr>
                        <td class="itemLable"> Call Number :</td>
                        <td class="itemValue">@Model.DeweyCallNumber </td>
                    </tr>
                    <tr>
                        <td class="itemLable">Replacement Cost:</td>
                        <td class="itemValue">@Model.Cost </td>
                    </tr>
                </table>

            </div>

        </div>
    </div>
</div>

Library/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Library/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Library/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
 
<div class="row">

    <div class="container">
        <div class="col-lg-3" style="background-color:darkorange; width:200px;height:250px;">
            <a asp-controller="Branch" asp-action="Index" class=""><h4> Branch</h4></a>

        </div>

        <div class="col-lg-4" style="background-color:cadetblue ;width:200px;height:250px; margin-left:30px ;margin-right:30px">
            <a asp-controller="Patron" asp-action="Index" class=""><h4 style="text-align:center"> Patrons</h4></a>

        </div>

        <div class="col-lg-4" style="background-color:darkgray ;width:200px;height:250px;">
            <a asp-controller="catalog" asp-action="Index" class=""><h4>catalog</h4></a>

        </div>
    </div>
</div>

Library/Views/Patron/Index.cshtml
@model Library.Models.Patron.ListOfPatronModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Profile Link</th>
            <th> FullName</th>
            <th>Library Card</th>
            <th>Fees</th>
            <th>Home Branch</th>


        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Patrons) {
        <tr>
            <td>
                <a asp-controller="Patron" asp-action="detalis" asp-route-id="@item.id">Profile</a>    </td>
            <td>
                @item.FullName
            </td>
            <td>
                @item.LibraryCardId
            </td>
            <td>
                @item.Fees
            </td>
            <td>
                @item.LibraryBranch
            </td>
        </tr>
}
    </tbody>
</table>

Library/Views/Patron/detalis.cshtml
@model Library.Models.Patron.PatronModel

@{
    ViewData["Title"] = "detalis";
}

<h2>detalis</h2>


<div class="row">

    <div class="col-xs-4" style="background-color:darkgrey">
        @Html.DisplayNameFor(model => model.id) :@Html.DisplayFor(model => model.id)
        <br />
        @Html.DisplayNameFor(model => model.FristName): @Html.DisplayFor(model => model.FristName)
        <br />
        @Html.DisplayNameFor(model => model.FullName) : @Html.DisplayFor(model => model.FullName)
        <br />
        @Html.DisplayNameFor(model => model.Address):  @Html.DisplayFor(model => model.Address)
        <br />
        @Html.DisplayNameFor(model => model.Telephone): @Html.DisplayFor(model => model.Telephone)
        <br />
        @Html.DisplayNameFor(model => model.MemberSice):@Html.DisplayFor(model => model.MemberSice)

    </div>

    <div class="col-xs-4" style="background-color:darkseagreen">
        @Html.DisplayNameFor(model => model.LibraryBranch):@Html.DisplayFor(model => model.LibraryBranch)
        <br />
        @Html.DisplayNameFor(model => model.Fees):  @Html.DisplayFor(model => model.Fees) $

    </div>
    <div class="col-xs-4" style="background-color:burlywood">
        @Html.DisplayNameFor(model => model.LibraryCardId):@Html.DisplayFor(model => model.LibraryCardId)
        <br />


    </div>
</div>
 <div style="text-align:center;margin-top:80px;">

     <a asp-action="Index">Back to List</a>
</div>

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Library A-Z</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>




    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        
        <header class="custom-header mdl-layout__header mdl-layout__header--waterfall">
            <div class="mdl-layout__header-row">

                <span class="mdl-layout-title glyphicon-log-out"><a href="/">Library A-Z</a> </span>
                <div class="mdl-layout-spacer">
                    <nav class="mdl-navigation mdl-layout--large-screen-only">


                    </nav>

                </div>


            </div>

        </header>


    </div>







     <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Library</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="text-align:center">
            <p>&copy; 2018 - Library</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>